package com.consultrio.quitplan

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.glance.appwidget.updateAll
import androidx.lifecycle.lifecycleScope
import com.consultrio.quitplan.data.*
import com.consultrio.quitplan.domain.*
import com.consultrio.quitplan.widget.SmokingWidget
import kotlinx.coroutines.launch
import java.time.*
import java.time.format.DateTimeFormatter
import kotlin.math.max

class MainActivity:ComponentActivity(){
 private lateinit var store:SettingsStore
 override fun onCreate(b:Bundle?){super.onCreate(b);store=SettingsStore(this);setContent{MaterialTheme{App()}}}
 @Composable private fun App(){var s by remember{mutableStateOf(store.load())};var tab by remember{mutableIntStateOf(0)};var refresh by remember{mutableIntStateOf(0)}
  if(!s.onboardingDone){Settings(s,true){s=it.copy(onboardingDone=true,planStartEpochDay=LocalDate.now().toEpochDay());store.save(s);refresh++};return}
  Scaffold(bottomBar={NavigationBar{listOf("Acasă","Plan","Progres","Istoric","Setări").forEachIndexed{i,n->NavigationBarItem(tab==i,{tab=i},{Text(listOf("⌂","▦","↗","≡","⚙")[i])},label={Text(n)})}}}){p->Box(Modifier.padding(p)){key(refresh){when(tab){0->Home(s){a->lifecycleScope.launch{register(a,s);refresh++;SmokingWidget().updateAll(this@MainActivity)}};1->Plan(s);2->Progress(s);3->History{refresh++};else->Settings(s,false){s=it;store.save(it);refresh++;lifecycleScope.launch{SmokingWidget().updateAll(this@MainActivity)}}}}}}
 }
 private fun learning(s:StoredSettings,d:LocalDate=LocalDate.now())=s.adaptiveWindows&&AdaptiveLearningEngine.isLearning(s.planStartEpochDay,s.learningDays,d)
 private fun target(s:StoredSettings,d:LocalDate=LocalDate.now())=if(learning(s,d))s.baseline else PlanEngine.targetForDay(s.baseline,if(s.adaptiveWindows)AdaptiveLearningEngine.reductionDayIndex(s.planStartEpochDay,s.learningDays,d) else max(0,(d.toEpochDay()-s.planStartEpochDay).toInt()),s.reductionAmount,s.reductionEveryDays)
 private suspend fun learned(s:StoredSettings,d:LocalDate=LocalDate.now()):List<SmokingWindow>{if(!s.adaptiveWindows||learning(s,d))return s.windows;val z=ZoneId.systemDefault();val start=LocalDate.ofEpochDay(s.planStartEpochDay).atStartOfDay(z).toInstant().toEpochMilli();return AdaptiveLearningEngine.learnedWindows(DatabaseProvider.get(this).smokingEventDao().eventsSince(start),d,s.wakeMinute,s.sleepMinute,s.weekdayLearning,z).ifEmpty{s.windows}}
 private suspend fun next(s:StoredSettings,last:SmokingEvent?,t:Int):Instant?{if(last==null)return null;val l=Instant.ofEpochMilli(last.estimatedStartAtMillis);return if(s.adaptiveWindows&&!learning(s))WindowPacingEngine.nextAllowedAt(l,t,s.wakeMinute,s.sleepMinute,learned(s)) else SmokingEngine.nextAllowedAt(l,PlanEngine.plannedIntervalMinutes(s.wakeMinute,s.sleepMinute,t))}
 private suspend fun register(a:SmokingActionType,s:StoredSettings){val t=target(s);if(t<=0)return;val dao=DatabaseProvider.get(this).smokingEventDao();val pressed=Instant.now();val est=SmokingEngine.estimatedStart(pressed,a,s.cigaretteDuration);val planned=next(s,dao.latest(),t);dao.insert(SmokingEvent(pressedAtMillis=pressed.toEpochMilli(),estimatedStartAtMillis=est.toEpochMilli(),actionType=a,plannedAtMillis=planned?.toEpochMilli(),deviationMinutes=SmokingEngine.deviationMinutes(est,planned)))}
 private fun bounds(d:LocalDate=LocalDate.now()):Pair<Long,Long>{val z=ZoneId.systemDefault();return d.atStartOfDay(z).toInstant().toEpochMilli() to d.plusDays(1).atStartOfDay(z).toInstant().toEpochMilli()-1}
 @Composable private fun Home(s:StoredSettings,onAction:(SmokingActionType)->Unit){var count by remember{mutableIntStateOf(0)};var last by remember{mutableStateOf<SmokingEvent?>(null)};var nxt by remember{mutableStateOf<Instant?>(null)};val t=target(s);LaunchedEffect(Unit){val dao=DatabaseProvider.get(this@MainActivity).smokingEventDao();val b=bounds();count=dao.countBetween(b.first,b.second);last=dao.latest();nxt=next(s,last,t)};var now by remember{mutableStateOf(Instant.now())};LaunchedEffect(nxt){while(true){now=Instant.now();kotlinx.coroutines.delay(1000)}};val day=(LocalDate.now().toEpochDay()-s.planStartEpochDay+1).toInt();val status=when{learning(s)->"Învățare · ziua ${day.coerceAtMost(s.learningDays)} din ${s.learningDays}. Nu reducem încă numărul de țigări.";t==0->"Plan încheiat · ținta este zero";nxt==null->"Înregistrează prima țigară când apare";nxt!!.isAfter(now)->"Următoarea țigară planificată în ${Duration.between(now,nxt).toMinutes()+1} min";else->"Poți fuma acum · ai amânat ${Duration.between(nxt,now).toMinutes()} min"}
  LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp),horizontalAlignment=Alignment.CenterHorizontally){item{Text("QuitPlan",style=MaterialTheme.typography.headlineMedium)};item{Card{Column(Modifier.padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("$count / $t azi",style=MaterialTheme.typography.displaySmall);Text(status);if(nxt!=null)Text("Ora planificată: "+nxt!!.atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("HH:mm")))}}};item{Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){Button({onAction(SmokingActionType.LIGHT_NOW)},enabled=t>0){Text("Aprind")};Button({onAction(SmokingActionType.SMOKING_NOW)},enabled=t>0){Text("Fumez")};Button({onAction(SmokingActionType.SMOKED)},enabled=t>0){Text("Am fumat")}}};item{Text(if(learning(s))"În această fază aplicația învață orele la care fumezi. După perioada setată începe reducerea și profilul se recalibrează continuu." else if(s.adaptiveWindows)"Profil adaptiv activ · distribuția țigărilor se ajustează după istoricul tău${if(s.weekdayLearning)" și ziua săptămânii" else ""}." else "Pacing uniform activ.")}}
 }
 @Composable private fun Plan(s:StoredSettings){val targets=PlanEngine.buildTargets(s.baseline,s.reductionAmount,s.reductionEveryDays);LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text("Planul de reducere",style=MaterialTheme.typography.headlineMedium);if(s.adaptiveWindows)Text("Primele ${s.learningDays} zile: învățare fără reducere. Apoi începe planul de reducere.")};if(s.adaptiveWindows)items(s.learningDays){i->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(14.dp).fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(LocalDate.ofEpochDay(s.planStartEpochDay).plusDays(i.toLong()).toString());Text("${s.baseline} · învățare")}}};items(targets.take(120).withIndex().toList()){(i,t)->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(14.dp).fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(LocalDate.ofEpochDay(s.planStartEpochDay).plusDays((i+(if(s.adaptiveWindows)s.learningDays else 0)).toLong()).toString());Text("$t țigări")}}}}}
 @Composable private fun Progress(s:StoredSettings){var actual by remember{mutableIntStateOf(0)};val elapsed=max(1,(LocalDate.now().toEpochDay()-s.planStartEpochDay+1).toInt());LaunchedEffect(Unit){val z=ZoneId.systemDefault();actual=DatabaseProvider.get(this@MainActivity).smokingEventDao().countSince(LocalDate.ofEpochDay(s.planStartEpochDay).atStartOfDay(z).toInstant().toEpochMilli())};val avoided=max(0,s.baseline*elapsed-actual);val saved=avoided*(s.packPrice/s.packSize);Column(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("Progres",style=MaterialTheme.typography.headlineMedium);Metric("Țigări evitate",avoided.toString());Metric("Economisit","%.2f lei".format(saved));Metric("Pachete evitate","%.1f".format(avoided.toDouble()/s.packSize));Metric("Profil adaptiv",if(s.adaptiveWindows)if(learning(s))"Învățare" else "Activ" else "Oprit")}}
 @Composable private fun Metric(n:String,v:String){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(n);Text(v,style=MaterialTheme.typography.headlineSmall)}}}
 @Composable private fun History(changed:()->Unit){var es by remember{mutableStateOf(emptyList<SmokingEvent>())};fun load(){lifecycleScope.launch{es=DatabaseProvider.get(this@MainActivity).smokingEventDao().recent()}};LaunchedEffect(Unit){load()};LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text("Istoric",style=MaterialTheme.typography.headlineMedium)};items(es,key={it.id}){e->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(12.dp).fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(Instant.ofEpochMilli(e.estimatedStartAtMillis).atZone(ZoneId.systemDefault()).format(DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm")),Modifier.weight(1f));TextButton({lifecycleScope.launch{DatabaseProvider.get(this@MainActivity).smokingEventDao().deleteById(e.id);load();changed()}}){Text("Șterge")}}}}}}
 @Composable private fun Settings(initial:StoredSettings,onboarding:Boolean,onSave:(StoredSettings)->Unit){var baseline by remember{mutableStateOf(initial.baseline.toString())};var wake by remember{mutableStateOf(fmt(initial.wakeMinute))};var sleep by remember{mutableStateOf(fmt(initial.sleepMinute))};var reduction by remember{mutableStateOf(initial.reductionAmount.toString())};var every by remember{mutableStateOf(initial.reductionEveryDays.toString())};var duration by remember{mutableStateOf(initial.cigaretteDuration.toString())};var price by remember{mutableStateOf(initial.packPrice.toString())};var size by remember{mutableStateOf(initial.packSize.toString())};var owned by remember{mutableStateOf(initial.packsOwned.toString())};var adaptive by remember{mutableStateOf(initial.adaptiveWindows)};var learnDays by remember{mutableStateOf(initial.learningDays.toString())};var weekday by remember{mutableStateOf(initial.weekdayLearning)}
  LazyColumn(Modifier.fillMaxSize().padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text(if(onboarding)"Configurează planul" else "Setări",style=MaterialTheme.typography.headlineMedium)};item{Num("Țigări pe zi acum",baseline){baseline=it}};item{TextField(wake,{wake=it},label={Text("Trezire (HH:mm)")},modifier=Modifier.fillMaxWidth())};item{TextField(sleep,{sleep=it},label={Text("Somn (HH:mm)")},modifier=Modifier.fillMaxWidth())};item{Row(verticalAlignment=Alignment.CenterVertically){Switch(adaptive,{adaptive=it});Spacer(Modifier.width(10.dp));Text("Învățare adaptivă")}};if(adaptive){item{Num("Zile inițiale de învățare",learnDays){learnDays=it}};item{Row(verticalAlignment=Alignment.CenterVertically){Switch(weekday,{weekday=it});Spacer(Modifier.width(10.dp));Text("Ține cont de ziua săptămânii")}}};item{Num("Reduc cu câte țigări",reduction){reduction=it}};item{Num("La câte zile",every){every=it}};item{Num("Durata țigării (minute)",duration){duration=it}};item{Num("Preț pachet (lei)",price,true){price=it}};item{Num("Țigări/pachet",size){size=it}};item{Num("Pachete existente",owned,true){owned=it}};item{Button({onSave(initial.copy(baseline=baseline.toIntOrNull()?.coerceAtLeast(1)?:20,wakeMinute=parse(wake)?:420,sleepMinute=parse(sleep)?:1380,adaptiveWindows=adaptive,learningDays=learnDays.toIntOrNull()?.coerceIn(1,30)?:7,weekdayLearning=weekday,reductionAmount=reduction.toIntOrNull()?.coerceAtLeast(1)?:1,reductionEveryDays=every.toIntOrNull()?.coerceAtLeast(1)?:1,cigaretteDuration=duration.toIntOrNull()?.coerceAtLeast(1)?:5,packPrice=price.replace(',','.').toDoubleOrNull()?.coerceAtLeast(0.0)?:30.0,packSize=size.toIntOrNull()?.coerceAtLeast(1)?:20,packsOwned=owned.replace(',','.').toDoubleOrNull()?.coerceAtLeast(0.0)?:0.0))},Modifier.fillMaxWidth()){Text(if(onboarding)"Începe planul" else "Salvează")}}}
 }
 @Composable private fun Num(l:String,v:String,d:Boolean=false,on:(String)->Unit){TextField(v,on,label={Text(l)},keyboardOptions=KeyboardOptions(keyboardType=if(d)KeyboardType.Decimal else KeyboardType.Number),modifier=Modifier.fillMaxWidth())}
 private fun fmt(m:Int)="%02d:%02d".format((m/60)%24,m%60);private fun parse(v:String):Int?{val p=v.split(":");if(p.size!=2)return null;val h=p[0].toIntOrNull()?:return null;val m=p[1].toIntOrNull()?:return null;return if(h in 0..23&&m in 0..59)h*60+m else null}
}
